name: jappeos_desktop_ui
description: Provides user interfaces for the JappeOS Desktop UI.

publish_to: 'none'
version: 1.0.0+1
google_sign_in_web: ^0.9.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_menu: ^0.4.1
  provider: ^6.0.3

  shade_theming:
    git:
      url: https://github.com/Jappe-OS/ShadeTheming.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  
  uses-material-design: true

  assets:
    - resources/images/blur_noise.png
